modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="runecraft" #mandatory
version="1.0" #mandatory
displayName="RuneCraft" #mandatory
logoFile="example.png" #optional
credits="Cray Jrt" #optional
authors="GUY AGAIN!! TOADIE!!" #optional
description=''' ELEMENTS AND R U N E S
'''